AHAHAHHAHAHAHAH

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,7 +3,7 @@ name: CI/CD Pipeline
 on:
   push:
     branches:
-      - lab3
+      - main
 
 jobs:
   RunMake:
@@ -25,6 +25,10 @@ jobs:
           cmake .. -DBUILD_SHARED_LIBS=ON -DENABLE_BENCHMARK=OFF -DCMAKE_INSTALL_PREFIX=/usr
           make -j$(nproc)
           sudo make install
+
+      - name: Проверяем, где установилась библиотека prometheus-cpp
+        run: |
+          find / -name "libprometheus-cpp*" 2>/dev/null || echo "Library not found!"
 
       - name: Run Make
         run: |
