Fix paths

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,23 +19,15 @@ jobs:
         run: |
           cd src
           make || { echo "Make failed"; exit 1; }
-          ls -l
-          mkdir -p ../usr/bin
-          cp fibonacci ../usr/bin/ || { echo "Failed to copy fibonacci"; exit 1; }
-          rm -f fibonacci
-
-      - name: Check if artifact exists
-        run: |
-          if [ ! -f ../usr/bin/fibonacci ]; then
-            echo "fibonacci was not found in ../usr/bin/"
-            exit 1
-          fi
+          ls -l  # Проверяем, что файл fibonacci существует в папке ../usr/bin
+          mkdir -p ../artifacts
+          cp ../usr/bin/fibonacci ../artifacts/ || { echo "Failed to copy fibonacci to artifacts"; exit 1; }
 
       - name: Upload Artifact (Binary)
         uses: actions/upload-artifact@v4
         with:
           name: fibonacci-binary
-          path: ../usr/bin/fibonacci
+          path: artifacts/
 
   RunTest:
     needs: RunMake
@@ -78,13 +70,7 @@ jobs:
           mkdir -p artifacts/deb/usr/local/bin
           mkdir -p artifacts/deb/DEBIAN
           cp DEBIAN/control artifacts/deb/DEBIAN/
-
-          if [ ! -f artifacts/fibonacci ]; then
-            echo "fibonacci not found in artifacts/"
-            exit 1
-          fi
-
-          cp artifacts/fibonacci artifacts/deb/usr/local/bin/
+          cp ../usr/bin/fibonacci artifacts/deb/usr/local/bin/  # Исправление пути
           dpkg-deb --build artifacts/deb fibonacci.deb
 
       - name: Upload Debian Package
